title: Alchemy.js documentation site
source: app/docs/
destination: .tmp/docs/
exclude: [misc/, styles/scss, js/coffee]

markdown: kramdown
# pygments: true
# highlighter: pygments
kramdown:
    hard_breaks: true
    toc_levels: 1..6
    use_coderay: true
    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      table
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               class

collections:
- documentation
- configDocs
- apiDocs
